version: "3"
services:
  web:
    container_name: larabug
    build:
      context: ""
      dockerfile: Dockerfile
    working_dir: /var/www/
    depends_on: [ db ]
    volumes:
      - ../.:/var/www
    networks:
      - larabug

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: larabug
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./db-data:/var/lib/mysql
    networks:
      - larabug

  webserver:
    image: nginx:stable-alpine
    depends_on: [ web ]
    volumes:
      - ../.:/var/www/
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - "1337:80"
    networks:
      - larabug

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on: [ db ]
    ports:
      - "8010:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
    networks:
      - larabug

networks:
  larabug:
    driver: bridge